# -*- coding: utf-8 -*-
"""Mod1_Exercise

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vzdZnL4zydjQmQ_xe6yuYng6o07p1pgo
"""

print("Olá mundo!")

qtd_total_vendas_1901 = 3
ticket_medio_1901 = 320.52

valor_total_vendas_2001 = 834.47
ticket_medio_2001 = 119.21

valor_total_vendas_2301 = 15378.12
qtd_total_vendas_2301 = 5

# Resultado (A)
valor_total_vendas_1901 = qtd_total_vendas_1901 * ticket_medio_1901
print(valor_total_vendas_1901)

# Resultado (B)
qtd_total_vendas_2001 = valor_total_vendas_2001 / ticket_medio_2001
print(int(qtd_total_vendas_2001))

# Resultado (C)
ticket_medio_2301 = valor_total_vendas_2301 / qtd_total_vendas_2301
print(round(ticket_medio_2301,2))

cancao = 'Roda mundo, roda gigante, roda moinho, roda pião.'

# Método 1: Lower
cancao_minusculo = cancao.lower()
print(cancao_minusculo)

# Método 2: Count
print(cancao_minusculo.count('roda'))

# Método 3: Find
posicao_ponto = cancao_minusculo.find('.')
print(posicao_ponto)

# Método 4: Split
cancao_minusculo_sem_ponto = cancao_minusculo[0:48]
print(cancao_minusculo_sem_ponto)

# Método 5: Split com o elemento ',' e transformação em lista
elementos_cancao_lista = cancao_minusculo_sem_ponto.rsplit(',')
print(elementos_cancao_list)

noticia = 'Selic vai a 2,75% e supera expectativas; é a primeira alta em 6 anos.'

posicao_2 = noticia.find('2')
# print(posicao_2)
posicao_porcent = noticia.find('%')
# print(posicao_porcent)
posicao_ano_6 = noticia.find('6 anos')
# print(posicao_ano_6)

# Selic
selic = noticia[12:17]
print(selic)

# Imprimir o valor do ano? De quando é a notícia? Estamos falando que é a primeira alta em 6 anos, mas não damos nenhuma referência de qual ano estamos.
# Por isso vou imprimir o '6 anos', ok?
ano = noticia[62:-1]
print(ano)

a = False
b = True

x = not(a & b)
print(x)