# -*- coding: utf-8 -*-
"""Mod2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mvcGhXLKIzrNoW9Cl66jWqN9sLIZKm5i
"""

dia_11_saldo_inicial = 1000
dia_11_transacao_1 = 243
dia_11_transacao_2 = -798.58
dia_11_transacao_3 = 427.12
dia_11_transacao_4 = -10.91
dia_11_saldo_final = dia_11_saldo_inicial + dia_11_transacao_1 + dia_11_transacao_2 + dia_11_transacao_3 + dia_11_transacao_4
print(dia_11_saldo_final)

usuario_web = ['André Perez', 'andre.perez', 'andre123', 'andre.perez@gmail.com']
print(usuario_web)
print(type(usuario_web))

idade = 20
saldo_em_conta = 723.15
usuario_loggedin = True
usuario_web = ['André Perez', idade, 'andre.perez', 'andre123', 'andre.perez@gmail', saldo_em_conta, usuario_loggedin]
print(usuario_web)
print(type(usuario_web))

fabricantes_mobile_china = ['xiaomi','samsung']
fabricantes_mobile_eua = ['apple','motorola']
print('china: ' + str(fabricantes_mobile_china))
print('eua: ' + str(fabricantes_mobile_eua))

fabricantes_mobile_china = ['xiaomi','samsung']
fabricantes_mobile_eua = ['apple','motorola']
fabricantes_mobile_china[1] = 'nokia'
print(fabricantes_mobile_china)

email = 'andre.perez@gmail.com'
caracteres_email = list(email)
print(email)
print(caracteres_email)

dia_11_saldo_inicial = 1000
dia_11_transacoes = list()
dia_11_transacoes.append(243)
dia_11_transacoes.append(-798.58)
dia_11_transacoes.append(427.12)
dia_11_transacoes.append(-10.91)
print(dia_11_transacoes)
dia_11_saldo_final = dia_11_saldo_inicial + dia_11_transacoes[0] + dia_11_transacoes[1] + dia_11_transacoes[2] + dia_11_transacoes[3]
print(dia_11_saldo_final)

brasil = {'capital': 'Brasília', 'idioma': 'Português', 'populacao': 210}
print(brasil)
print(type(brasil))

carro = {
    'marca': 'Volkswagen',
    'modelo': 'Polo',
    'ano': 2021,
    'ano': 2004
}
print(carro)

cadastro = {
    'andre': {
        'nome': 'Andre Perez', 
        'ano_nascimento': 1992, 
        'pais': {
            'pai': {
              'nome': '<nome-do-pai> Perez', 
              'ano_nascimento': 1971
            },
            'mae': {
              'nome': '<nome-da-mae> Perez', 
              'ano_nascimento': 1973
            },
        }
    }
}
print(cadastro)
cadastro['andre']['pais']['mae']['nome']

credito = {'123': 750,'789': 980}
score_123 = credito['123']
score_789 = credito['789']
print(score_123)
print(score_789)

credito['123'] = 435
print(credito)
score_123 = credito['123']
print(score_123)

credito['544'] = 888
print(credito)

artigo = dict(
    titulo='Modulo 02 | Python: Estruturas de Dados',
    corpo='Topicos, Aulas, Listas, Conjuntos, Dicionários, ...',
    total_caracteres=1530
)
print(artigo)

artigo.update({'total_caracteres': 7850})
print(artigo)

total_caracteres = artigo.pop('total_caracteres')
print(total_caracteres)

artigo = dict(
    titulo='Modulo 02 | Python: Estruturas de Dados',
    corpo='Topicos, Aulas, Listas, Conjuntos, Dicionários, ...',
    total_caracteres=1530
)
print(artigo)

chaves = list(artigo.keys())
print(chaves)

valores = list(artigo.values())
print(valores)

wifi_disponiveis = list()

rede = {'nome': 'rede1', 'senha': 'cnx_cnx'}
wifi_disponiveis.append(rede)

rede = {'nome': 'uai-fi', 'senha': 'r3d3'}
wifi_disponiveis.append(rede)

print(wifi_disponiveis)